### PR TITLE
Add tooltip next to 'Implementation period'

### LINKED ISSUE #107: Add tooltip next to 'Implementation period'
**Is your feature request related to a problem? Please describe.**
The 'implementation period' is a stranger concept in v2 of the cost calculator, since it's a little more focused on returning-to-2019-baseline and a little less focused on implementing revocations reductions.

**Describe the solution you'd like**
We'd like to add a tooltip or on-hover description to the 'Implementation period' label, to make it easy for users to understand what this means / that it's really more of a transition period.

The copy for the on-hover dialog is being drafted, feel free to use Lorem Ipsum for now.

**Additional context**
- Mocks coming soon. Assigning to Juan for mock-ups. @agronomic when you've attached mocks, please reassign to @nasaownsky
- We should ensure this works on-tap on mobile, as well.

### PR DESCRIPTION
**Pull request by nasaownsky**
## Description of the change

Added tooltip next to Implementation period

lg: 
Снимок экрана 2021-09-01 в 13 54 28

md:
Снимок экрана 2021-09-01 в 13 55 50

sm:
Снимок экрана 2021-09-01 в 13 56 08

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #107 

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by nasaownsky** [comment]
Hey @jessex @cawarren! So I've placed tooltip in positions different than in mocks, but I think it just feels better with this positioning. Pictures in the description. Let me know you thoughts!

**Comment by cawarren** [comment]
I agree with the approach you took, thanks for playing around to find a
better option!

**Review by jessex — COMMENTED** [review]
This looks great, @nasaownsky!

@cawarren we just need the final copy to add here and then we can merge this in.

**Comment by cawarren** [comment]
Thank you! Copy is:

> The transition time frame over which changes might take effect. The model will phase in the outcomes gradually over the implementation period.

**Comment by nasaownsky** [comment]
@jessex should be ready to merge!

**Pull request merged**
