### PR TITLE
Banner fix

### LINKED ISSUE #116: Chart for Alaska shows very little 2020 change, until you set the scenario to it
**Describe the bug**
If you select Alaska, the line chart shows almost no population change (including in 2020). However, once you click the '2020' button in thew new banner, it shows a significant reduction - again, after 2020. This is odd, since that button maintains the drop in 2020. 

**To Reproduce**
1. Select Alaska
2. Note the line chart is pretty flat
image

3. Click the 'Maintain 2020 levels' button
4. Note the line chart now shows a (correct) reduction to 2020 levels. But why doesn't it show 2020, itself, being at these levels?
image

**Expected behavior**
I'd expect 2020 would have the same changes as maintaining it does. I think the 'maintained' changes are correct, looking at the underlying data. So I'm not sure why the year 2020 itself seems flat.

**Desktop (please complete the following information):**
 - OS [e.g. Windows 10]: Chrome OS
 - Browser [e.g. chrome, edge]: Google Chrome
 - Version [e.g. 22]: 92.0.4515.162 (Official Build) (64-bit)

params.csv file used to test has been emailed.

### LINKED ISSUE #117: The [Maintain 2020 levels] button always uses the same hard-coded 2020 reduction amounts
**Describe the bug**
On all states, clicking the [Maintain 2020 levels] in the banner always adjusts the sliders in the same way - (-21%) for revocations, and (-14%) for new admissions. This is my fault for being unclear in the initial feature request. 

What we want want is for that button to set the sliders, so that the state maintains at the 2020 levels of both admissions and revocations. That will be a different amount, for each slider, in every state.  

**To Reproduce**
1. Go to any state
2. Click the banner button, 'Maintain 2020 levels'
3. Note that the sliders jump to -21% / -14%
4. This is consistent on all states

**Expected behavior**
When the 'Maintain 2020 levels' button is clicked, the sliders should jump to the percent reduction that 2020 is below 2019 for both Revocations and Admissions.

### PR DESCRIPTION
**Pull request by nasaownsky**
## Description of the change

Removed `Maintain 2020 levels` button & changed copy text

## Type of change

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #116 , Closes #117 

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [ ] This pull request has a descriptive title and information useful to a reviewer
- [ ] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [ ] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by nasaownsky** [comment]
@cawarren Hey! As you has mentioned in #117, I do not have enough information to tell which exactly percent reduction that 2020 is below 2019 for both Revocations and Admissions should be. So I took 2nd approach you offered. Also, we could keep `Reset` button, as its kinda improves UX by letting the user to reset all sliders w/o switching the states.

**Comment by cawarren** [comment]
Thanks Ilya! That makes sense to me.

**Comment by nasaownsky** [comment]
@cawarren Also, I assume that #116 problem is having these constants instead of dynamic values, am I right? If so, we also could close #116 within this PR.

**Comment by cawarren** [comment]
Yes I suspect you're right, thanks Ilya!

**Comment by cawarren** [comment]
Unfortunately @jessex is out this week, but we don't have more time on this project. I'm going to approve and merge this PR, but Josh may have comments / request additional changes he requests after the fact. Thanks again for your work on this, @nasaownsky.

**Review by jessex — COMMENTED** [review]
Just a post hoc check-in for you, @cawarren: this looks good! No concerns. Thanks for merging.

**Pull request merged**
