### PR TITLE
Re-introduce use of 'Data Year' column for starting year

### LINKED ISSUE #98: Re-introduce use of 'Data Year' column for starting year
**Is your feature request related to a problem? Please describe.**
In the original cost calculator, some data was from 2019 and other data was older (e.g., from 2017). To differentiate these, the second column of the params.csv file was `Data Year`, which included which year the data was from.

We've lost that in the update (this was our fault, in building the revised spreadsheet / inputs), and as a result we can't include several states that have older data. We should add this column back in, so that we can include those states with older data again.

**Describe the solution you'd like**
The `params.csv` file will be the same, but include a new column as the second column: `Data Year`.

The component should use this new column to update several strings in the UI:
- Under the state name selector, it should read "Based on [State Name] data from [`Data Year`], 2020". If 2020 data is not included, it should only mention the data year.
- Under the Outcomes section on the left, the string should read "From [Data Year] baseline"
- The X-axis should begin with the value in [Data Year], instead of "2019"

(I realize that last one might be visually confusing for someone, since the x-axis would say '2017   2020   2021   2022...', but I think that's an okay compromise to make.)

**Describe alternatives you've considered**
- We could continue to just stick with states that have 2019 data, but this leaves many states out of the calculator.
 
**Additional context**
An example `params` file is attached.
[params_revised.csv](https://github.com/Recidiviz/supervision-success-component/files/6972561/params_revised.csv)

Some clarifying points:
- 2020 should still be the 'special' year that projections jump off from, and that has the gray background if data is unavailable.
- The chart should pretend that years between the `Data Year` and 2020 don't exist (so the x-axis of the chart may go from 2017 to 2020 to 2021...)

### PR DESCRIPTION
**Pull request by nasaownsky**
## Description of the change

Re-introduce use of 'Data Year' column for starting year

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (adjusts configuration to achieve some end related to functionality, development, performance, or security)

## Related issues

> Closes #98 

### Development

These boxes should be checked by the submitter prior to merging:

- [x] Manual testing against realistic data has been performed locally

### Code review

These boxes should be checked by reviewers prior to merging:

- [x] This pull request has a descriptive title and information useful to a reviewer
- [x] This pull request has been moved out of a Draft state, has no "Work In Progress" label, and has assigned reviewers
- [x] Potential security implications or infrastructural changes have been considered, if relevant

### CODE REVIEW

**Comment by cawarren** [comment]
@nasaownsky Would you mind updating the `Readme` file to include the new column as well?

I've tested this change in the browser, and it appears to work perfectly to me. I think this may be the last issue for this feature - amazing job pulling it together and through the finish line.

**Review by jessex — CHANGES_REQUESTED** [review]
Great work, @nasaownsky! Like @cawarren, I see no issues here. Besides my in-line comment, I second @cawarren's request to update the README to include the new column in its right place.

**Comment by nasaownsky** [comment]
@jessex @cawarren Done!

**Review by jessex — APPROVED** [review]
States with 2019 or earlier base data years, with and without 2020 data available, all function as expected. Thanks, @nasaownsky!

**Pull request merged**
